import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/Link'
import React from 'react';
// import { BrowserRouter, Routes, Route, Link} from 'react-router-dom';
// import Index from './Index';
import New from '../components/New';
import Edit from '../components/Edit';
import Search from '../components/Search'
import Index from '../components/Index'
import App from '../components/App'
import Select from './select'

// import axios from 'axios';
// import './Index.css';
// import '../css/tailwind.css';

const Home = (props) => {
    return (
      <div>
          <Select />
        <h2>
            POSTの一覧
          </h2>
            <Index 
              tasks={props.tasks}
            />
            {/* {props.task_id} */}
          <h2><Link href="/tasks">Back to home</Link></h2>
      </div>
    )
  }
  
  export const getStaticProps = async () => {
    // URLはlocalhostではなくapiとなる
    const tasks = await fetch("http://api:3000/tasks", {method: "GET"});
    const json = await tasks.json();

    // const task_id = await fetch(`http://api:3000/tasks/${2}`, {method: "GET"});
    // const json_task = await task_id.json();

    return {
      props: {
        tasks: json,
        // task_id: json_task
      },
    };
  }
  
  export default Home;

// export default function Home() {
    // let selects = ["list", "new", "search"]
    // let value;
    // selects.map((select) => {
    //     value = select
    // })
//   return (
//     <>
        
        {/* <p>
            <Link href="../components/Index"><a>投稿一覧</a></Link>
        </p>
        <p>
            <Link href="/components/New"><a>新規投稿</a></Link>
        </p>
        <p>
            <Link href="/components/Search"><a>投稿検索</a></Link>
        </p> */}
        {/* <App /> */}
    // </>
    // <div className="w-5/12 flex justify-center">
    //     <select  value={value}>
    //         <option value="list"><Link href="list"><a>投稿一覧</a></Link></option>
    //         <option value="new"><Link href="new"><a>新規投稿</a></Link></option>
    //         <option value="search"><Link href="search"><a>投稿検索</a></Link></option>
    //     </select>
    //     <Link href="list"><a>投稿一覧</a></Link>
    // </div>
    // <App />
    // <div className={styles.container}>
    // <App />
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //     <h1 className={styles.title}>
    //       Read <Link href="post"><a>this page!</a></Link>
    //       {/* Welcome to <a href="index">this page!</a> */}
    //     </h1>

    // </div>
//   )
// }
// export default Home;

// import React from 'react';
// // import { BrowserRouter, Routes, Route, Link} from 'react-router-dom';
// // import Index from './Index';
// import New from '../components/New';
// import Edit from '../components/Edit';
// import Search from '../components/Search'
// // import axios from 'axios';
// // import './Index.css';
// // import '../css/tailwind.css';

// class App extends React.Component {
//     constructor(props) {
//         super(props)
//         this.state = {
//             filter: "index"
//         }
//     }

//     componentDidMount() {
//         axios.get('/modes.json')
//         .then(resp => {
//             var mode = resp.data.map((filter) => filter.filter)
//             this.setState({filter: mode[0]});
//         });
//     }
    
//     handleChange(event) {
//         var data = {
//             filter: event
//         }
//         this.setState({filter: event})
//         axios.post('/modes', data)
//         .then(resp => {
//             this.setState({filter: event});
//         });
//     }
    
//     render() {
//         let getFilter;
//         if (this.state.filter === "index") {
//             getFilter = <Index />
//         } else if (this.state.filter === "new") {
//             getFilter = <New />
//         } else {
//             getFilter = <Search />
//         }
    
//         return(
            
//             <div>
//                 <div className="w-5/12 flex justify-center">
//                     <select value={this.state.filter} onChange={e => this.handleChange(e.target.value)}>
//                         <option value="index">投稿一覧</option>
//                         <option value="new">新規投稿</option>
//                         <option value="search">投稿検索</option>
//                     </select>
//                 </div>
//                 {getFilter}
//             </div>
//         )
            
//         }
//     }

// export default App;